import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
  gettingStartedSidebar: [{type: 'autogenerated', dirName: 'getting-started'}],
  hardwareSidebar: [{type: 'autogenerated', dirName: 'hardware'}],
  developerSidebar: [{type: 'autogenerated', dirName: 'developer'}],
};

export default sidebars;
